stages:
    - build

image: docker:stable

build-architectures:
    stage: build

    variables:
        REPO_DIR_NAME: "python-architectures"

    script:
        - apk add rpm
        - apk add wget
        - apk add python2
        - wget -O get-pip2.py https://bootstrap.pypa.io/pip/2.7/get-pip.py
        - python2 get-pip2.py
        - python2 setup.py bdist_rpm --requires "python2-defaults,python2-factory"
        - apk add python3
        - wget -O get-pip3.py https://bootstrap.pypa.io/get-pip.py
        - python3 get-pip3.py
        - python3 setup.py bdist_rpm --requires "python3-defaults,python3-factory"
        - mkdir $REPO_DIR_NAME
        - cp dist/*.rpm $REPO_DIR_NAME
    tags:
        - docker
    artifacts:
        paths:
            - $REPO_DIR_NAME/*
