stages:
    - build

build-architectures:
    stage: build

    variables:
        REPO_DIR_NAME: "python-architectures"

    script:
        - wget -O get-pip2.py https://bootstrap.pypa.io/pip/2.7/get-pip.py
        - python2 get-pip2.py
        - python2 setup.py bdist_rpm --fix-python
            --requires "python2-defaults,python2-factory"
        - wget -O get-pip3.py https://bootstrap.pypa.io/get-pip.py
        - python3 get-pip3.py
        - python3 setup.py bdist_rpm --fix-python
            --requires "python3-defaults,python3-factory"
        - mkdir $REPO_DIR_NAME
        - cp dist/*.rpm $REPO_DIR_NAME
        - createrepo $REPO_DIR_NAME
        - chmod og= $ID_RSA
        - scp -i $ID_RSA -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -r $REPO_DIR_NAME $SERVER_USER@$SERVER_IP$SERVER_ROOT_PATH
    tags:
        - pbitlab
    artifacts:
        paths:
            - $REPO_DIR_NAME/*
